### PR TITLE
Upgrade to webpack 5

### PR DESCRIPTION
**Pull request by 0xln**
To address [Upgrade to webpack 5](https://github.com/philipmw/phrase.shop/issues/22) issue.

### CODE REVIEW

**Comment by 0xln** [comment]
In the spirit of hacktoberfest, please can the label `hacktoberfest-accepted` be added to this PR

**Comment by philipmw** [comment]
@0xln thank you for your contribution -- I am excited to receive it!

I tested `npm start` and that works well, but it no longer auto-opens a browser window. I kinda like that, though. The bigger issue is that `npm run build` no longer works. It gives this error:

> [webpack-cli] Unknown argument: --display-error-details

I am quite sure I can fix this myself, but I figure it's best if you fix it so we can merge a fully functional pull request from you.

Would you please fix `npm run build`?

Thank you, looking forward to the next revision!

**Comment by philipmw** [comment]
FYI, I added the "hacktoberfest" topic to this repo.

**Comment by 0xln** [comment]
Going to make an adjustment to get the `npm build step` sorted and once that is done, the PR should be all good. Thanks for adding hacktoberfest to the topic!

**Comment by philipmw** [comment]
Thanks very much for your contribution, 0xln! I hope you get and enjoy that t-shirt. :)

**Pull request merged**
