### PR TITLE
Add US Airport codes as option

### PR DESCRIPTION
**Pull request by 0xln**
Added airport codes as a phrase type, taken from [Passenger Boarding (Enplanement) and All-Cargo Data for U.S. Airports
Airports](https://www.faa.gov/airports/planning_capacity/passenger_allcargo_stats/passenger/). 

Addresses issue [Add airport codes as a phrase part type](https://github.com/philipmw/phrase.shop/issues/10)

### CODE REVIEW

**Comment by philipmw** [comment]
Hey there, @0xln! Happy weekend!

Thanks for the PR. I have two concerns.

One, you are adding about 522 airports. I believe that's still too many for good memorization, and I'd prefer to have that number reduced to just the most popular airports. For example, the top 16, or at most the top 32. That feels like a good tradeoff between variety and memorability.

Two, the number of entropy bits this word type is advertising does not match reality. You are advertising 4 bits, which allows for 16 possibilities, but you're adding 522 airports. The actual number of bits right now is about 9, which is log-base-2 of 522.

If it was me, I'd keep the number of bits advertised as-is at 4, and reduce the number of airports in the wordbank to the top 16 commercial airports. How do you feel about that?

Did you type all those by hand? 🤭

**Comment by 0xln** [comment]
I did a quick cut and paste job, so not typed by hand thankfully!
I've adjusted the airports to the top 16, so that it matches the entropy provided and makes them slightly more memorable. Maths never was my strong point 🙃

**Comment by philipmw** [comment]
Nice! Can you just double-check that `coverage/lcov.info` does not need to change with your latest commit?

**Comment by 0xln** [comment]
Yep, looks like it did need an update. Fixed!

**Comment by philipmw** [comment]
Woohoo!

**Pull request merged**
